version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - .:/routers-redux-react
    container_name: routers-redux-react-c
    image: routers-redux-react-img
    ports:
      - 3000:3000
    command: npm start
    environment:
      - WACTHPACK_POLLING=true
